language: java

jdk:
  - oraclejdk8

os:
  - linux

before_install:
 - chmod +x gradlew

notifications:
  slack: htisolutions:YdWkXIDUZB1cdVMdKdrQGAN8
  email: false

script:
  - ./gradle clean build
